id: P007974
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:41.597474
source_metadata:
  id: bdr:W26677
  title: རྫོགས་ཆེན་ཁྲིད་སྐོར་བདུད་འཇོམས་གླིང་པའི་གཏེར་ཆོས
  author: ''
  volumes:
    9558e725a4ee4ffb956086942697eaab:
      image_group_id: I5667
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
